In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("candy-data.csv", delimiter = ",", index_col='competitorname')

In [3]:
train_data = data.drop(["One quarter", "Peanut butter M&Ms"])

In [4]:
x = pd.DataFrame(train_data.drop(['winpercent'], axis=1))
y = pd.DataFrame(train_data["winpercent"])

In [5]:
reg = LinearRegression().fit(x,y)

In [6]:
data.loc["One quarter"].to_frame().T

chocolate  fruity  caramel  peanutyalmondy  nougat  \
One quarter        0.0     0.0      0.0             0.0     0.0   

             crispedricewafer  hard  bar  pluribus  sugarpercent  \
One quarter               0.0   0.0  0.0       0.0         0.011   

             pricepercent  winpercent    Y  
One quarter         0.511   46.116505  0.0

In [7]:
onequarter = data.loc["One quarter"].to_frame().T
reg.predict(onequarter.drop(["winpercent", "Y"], axis = 1))

array([[27.38926659]])

In [8]:
data.loc["Peanut butter M&Ms"].to_frame().T

chocolate  fruity  caramel  peanutyalmondy  nougat  \
Peanut butter M&Ms        1.0     0.0      0.0             1.0     0.0   

                    crispedricewafer  hard  bar  pluribus  sugarpercent  \
Peanut butter M&Ms               0.0   0.0  0.0       1.0         0.825   

                    pricepercent  winpercent    Y  
Peanut butter M&Ms         0.651    71.46505  1.0

In [9]:
onequarter = data.loc["Peanut butter M&Ms"].to_frame().T
reg.predict(onequarter.drop(["winpercent", "Y"], axis = 1))

array([[70.6426544]])

In [17]:
reg.predict([[0, 1, 1, 1, 1, 0, 1, 1, 0, 0.505, 0.618]])

array([[44.77004263]])